POST http://localhost:5000/calendar/update HTTP/1.1
content-type: application/json

{
    "userId": "5f6f93220b3441f1f8ff4f02",
    "date": "2020-02-3",
    "menuItems": [
      {"foodId": "4", 
        "quantity": 3
      }, 
      {"foodId": "12", 
        "quantity": 1
       }]
}