POST http://localhost:5000/calendar/update HTTP/1.1
content-type: application/json

{
    "userId": "5f6f3d42cd9bedc5e0f8db81",
    "date": "28-8-2020",
    "menuItems": [
      {"foodId": "4", 
        "quantity": 3
      }, 
      {"foodId": "12", 
        "quantity": 1
       }]
}