POST https://ancient-fortress-30675.herokuapp.com/calendar/update HTTP/1.1
content-type: application/json

{
    "userId": "5fabc77774112f0017a7e7d9",
    "date": "12-11-2020",
    "menuItems": [
      {"foodId": "14", 
        "quantity": 3
      },
      {"foodId": "4", 
        "quantity": 13
      },
      {"foodId": "12", 
        "quantity": 3
      }
    ]
}