POST http://localhost:5000/calendar/update HTTP/1.1
content-type: application/json

{
    "userId": "5f7af44195b4a7b93672d146",
    "date": "9-10-2020",
    "menuItems": [
      {"foodId": "14", 
        "quantity": 3
      },
      {"foodId": "4", 
        "quantity": 13
      },
      {"foodId": "12", 
        "quantity": 3
      }
]
}